# Copyright 2025 The Nuclio Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "2"

run:
  timeout: 5m

linters:
  enable:
    - goconst
    - gofmt
    - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - errcheck
    - govet
    - typecheck
    - gocritic
    - unused
  settings:
    gocritic:
      disabled-checks:
        # we don't want to enforce space before the comment text
        - commentFormatting

formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - prefix(github.com/nuclio/nuclio/)
        - default
        - blank
        - dot
      custom-order: true
